language: php

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.1
  - 7.2

dist: trusty

addons:
  chrome: stable

before_install:
  #
  # webdriver setup
  #
  - mkdir -p $HOME/webdriver
  - wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip --directory-prefix=$HOME/webdriver
  - unzip $HOME/webdriver/chromedriver_linux64.zip -d $HOME/webdriver
  - rm $HOME/webdriver/chromedriver_linux64.zip
  - $HOME/webdriver/chromedriver &
  #
  # capture setup
  #
  - mkdir -p .travis/capture

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit
  - bin/simcap capture:page -c .travis/webdriver.yml .travis/capture_list.yml
