language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit
