#!/usr/bin/env php
<?php
mb_internal_encoding('UTF-8');

require __DIR__ . '/vendor/autoload.php';

use Momo\SimpleCaptureTool\Console\Application;

if (($pharArchivePath = Phar::running(false)) !== '') {
    $configDirectory = dirname($pharArchivePath);
} else {
    $configDirectory = __DIR__;
}

$application = new Application();
$application->setConfigDirectory($configDirectory);
$application->run();
