#!/usr/bin/env php
<?php
mb_internal_encoding('UTF-8');

require __DIR__ . '/vendor/autoload.php';

use Momo\Selenium\Console\Application;

$application = new Application();
$application->setConfigDirectory(__DIR__);
$application->run();
